#!/bin/bash
svn up acpicag
svn up ankhg
svn up boehm_gcg
svn up boost-liteg
svn up bootstrapg
svn up crtng
svn up cunitg
svn up cxxg
svn up cxx_libc_iog
svn up cxx_threadg
svn up dashg
svn up ddeg
svn up dde-libinputg
svn up demangleg
svn up dopeg
svn up driversg
svn up drivers-frstg
svn up examplesg
svn up expat2g
svn up fb-drvg
svn up fbterminalg
svn up fuxfprovg
svn up hellog
svn up inputg
svn up iog
svn up l4cong
svn up l4reg
svn up l4re_cg
svn up l4re_kernelg
svn up l4re_vfsg
svn up l4sysg
svn up l4utilg
svn up ldscriptsg
svn up ldsog
svn up lib_vt100g
svn up libbsdg
svn up libbsd-fullg
svn up libc_backendsg
svn up libc_be_stding
svn up libcryptog
svn up libeventg
svn up libgccg
svn up libgcc-pureg
svn up libgfxbitmapg
svn up libgompg
svn up libiniparserg
svn up libiog
svn up libio-iog
svn up libirqg
svn up libjpegg
svn up libkproxyg
svn up libloaderg
svn up libpngg
svn up libsdlg
svn up libsdl-imageg
svn up libsigma0g
svn up libstdc++-headersg
svn up libstdc++-v3g
svn up libstdc++-v3-minimalg
svn up libsupc++g
svn up libsupc++-minimalg
svn up libvbusg
svn up libvcpug
svn up linux-26-headersg
svn up loaderg
svn up logg
svn up luag
svn up lwipg
svn up lxfuxlibcg
svn up magg
svn up mag-gfxg
svn up moeg
svn up nedg
svn up ocamlg
svn up ocaml_toysg
svn up plrg
svn up pythong
svn up readlineg
svn up rtcg
svn up scoutg
svn up scout-gfxg
svn up serial-drvg
svn up shmcg
svn up sigma0g
svn up slabg
svn up spafsg
svn up sqliteg
svn up tlsfg
svn up tmpfsg
svn up uclibcg
svn up uclibc-headersg
svn up uclibc-minimalg
svn up udis86g
svn up valgrind
svn up x86emu
svn up zlib
